language: node_js
node_js:
  - "0.12"
env:
  - NODE_ENV=development
before_install:
  - npm install -g npm
  - npm install -g nodemon
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
before_script:
  - bower install
#addons:
#  code_climate:
#    repo_token: adf08323...
after_script:
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
  - ./node_modules/coveralls/bin/coveralls.js < ./reports/coverage/lcov.info
  - rm -rf ./reports/coverage
notifications:
  email:
    on_succes: always
    on_failure: always