language: node_js
node_js:
  - "0.12"
env:
  - NODE_ENV=development
before_install:
  - npm install -g npm
  - npm install -g nodemon
  - npm install -g grunt-cli
  - npm install -g bower
#  - npm install -g codeclimate-test-reporter
before_script:
  - bower install
#  - grunt build
#addons:
#  code_climate:
#    repo_token: adf08323...
#after_script:
#  - codeclimate-test-reporter < lcov.info
notifications:
  email:
    on_succes: always
    on_failure: always